name: sovann_and_ly
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.5.1
  material_symbols_icons: ^4.2785.1
  url_launcher: ^6.3.0
  intl: ^0.19.0
  animate_do: ^3.3.4
  photo_view: ^0.15.0
  go_router: ^14.4.1
  recase: ^4.1.0
  animated_text_kit: ^4.2.2
  visibility_detector: ^0.4.0+2
  flutter_svg: ^2.0.14
  firebase_core: ^3.0.0
  cloud_firestore: ^5.5.0
  keyboard_dismisser: ^3.0.0
  appwrite: ^13.0.0
  carousel_slider: ^5.0.0
  auto_size_text: ^3.0.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/decor/loading.svg
    - assets/decor/smoke_hearh.webp
    - assets/decor/sakura1.png
    - assets/decor/sakura2.png
    - assets/decor/map.svg
#    - assets/decor/name_intial.png
#    - assets/photo/intro_main.png
#    - assets/images/

  fonts:
    - family: Hatolie
      fonts:
        - asset: assets/font/Hatolie.ttf
    - family: Photograph Signature
      fonts:
        - asset: assets/font/photograph_signature.ttf
    - family: RetroSignature
      fonts:
        - asset: assets/font/RetroSignature.otf
    - family: Andasia
      fonts:
        - asset: assets/font/Andasia.ttf
    - family: WorldDiscovery
      fonts:
        - asset: assets/font/WorldDiscovery.otf
    - family: Madina
      fonts:
        - asset: assets/font/Madina.ttf
    - family: Batusa
      fonts:
        - asset: assets/font/Batusa.otf
    - family: HughIsLifePersonalUseItalic-K7axe
      fonts:
        - asset: assets/font/HughIsLifePersonalUseItalic-K7axe.ttf
    - family: KnightornsfreepersonaluseScrip-9M68K
      fonts:
        - asset: assets/font/KnightornsfreepersonaluseScrip-9M68K.otf

    - family: Metropolis-515rv
      fonts:
        - asset: assets/font/Metropolis-515rv.otf

    - family: Metropolis-6Y5M1
      fonts:
        - asset: assets/font/Metropolis-6Y5M1.ttf

    - family: HapshaSophiaScript-e91Yl
      fonts:
        - asset: assets/font/HapshaSophiaScript-e91Yl.otf

    - family: HelloGraduationScript-PKR3P
      fonts:
        - asset: assets/font/HelloGraduationScript-PKR3P.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700