// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGPSVlx8Nca2amVRn9IBLV9njVj5sH9sM',
    appId: '1:17558236151:web:d7233b782d0452da3fdcf2',
    messagingSenderId: '17558236151',
    projectId: 'wedding-4928e',
    authDomain: 'wedding-4928e.firebaseapp.com',
    storageBucket: 'wedding-4928e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc4VyxG9RfIGOTkSwKjeO03ZQF1DBC2fc',
    appId: '1:17558236151:android:166f35d763fccf903fdcf2',
    messagingSenderId: '17558236151',
    projectId: 'wedding-4928e',
    storageBucket: 'wedding-4928e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0DAkW_eDc6T1LASgPk-L1PDkp0Qc_2GU',
    appId: '1:17558236151:ios:3f20d24e7c31a8b63fdcf2',
    messagingSenderId: '17558236151',
    projectId: 'wedding-4928e',
    storageBucket: 'wedding-4928e.firebasestorage.app',
    iosBundleId: 'dev.sovann.sovannAndLy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0DAkW_eDc6T1LASgPk-L1PDkp0Qc_2GU',
    appId: '1:17558236151:ios:3f20d24e7c31a8b63fdcf2',
    messagingSenderId: '17558236151',
    projectId: 'wedding-4928e',
    storageBucket: 'wedding-4928e.firebasestorage.app',
    iosBundleId: 'dev.sovann.sovannAndLy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGPSVlx8Nca2amVRn9IBLV9njVj5sH9sM',
    appId: '1:17558236151:web:aa65421e5d04b11c3fdcf2',
    messagingSenderId: '17558236151',
    projectId: 'wedding-4928e',
    authDomain: 'wedding-4928e.firebaseapp.com',
    storageBucket: 'wedding-4928e.firebasestorage.app',
  );
}
